### ISSUE TITLE
ストレージに保存する際のボトルネック解消

### ISSUE THREAD

**Issue by nikawamikan** [CinnamonSea2073/Genshin-Discordbot#25]
ストレージに保存しなくても fileioのオブジェクトに保存することでメモリのみで完結するので修正すると良いです

https://github.com/CinnamonSea2073/Genshin-Discordbot/blob/f9987ccce3399c9f93ea0709e00041bfe49fbbf6/lib/getStat.py#L538-L542

```py
from io import BytesIO

        fileio = BytesIO()
        image.save(fileio, format="png")
        fileio.seek(0)
        return File(fp=fileio, filename="image.png")
```

**Comment by nikawamikan** [comment]
今回の画像生成関数にファイル出力とファイルのパスを生成する関数を定義したので上記の問題が解決するはずなので、それ結合テストで問題なければcloseしてOKです

**Comment by CinnamonSea2073** [comment]
お疲れ様でした〜
